// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/facade/session_action_handler.go

// Package mock_facade is a generated GoMock package.
package mock_facade

import (
	datamodel "github.com/RSE-Cambridge/data-acc/internal/pkg/datamodel"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSessionActionHandler is a mock of SessionActionHandler interface
type MockSessionActionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSessionActionHandlerMockRecorder
}

// MockSessionActionHandlerMockRecorder is the mock recorder for MockSessionActionHandler
type MockSessionActionHandlerMockRecorder struct {
	mock *MockSessionActionHandler
}

// NewMockSessionActionHandler creates a new mock instance
func NewMockSessionActionHandler(ctrl *gomock.Controller) *MockSessionActionHandler {
	mock := &MockSessionActionHandler{ctrl: ctrl}
	mock.recorder = &MockSessionActionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSessionActionHandler) EXPECT() *MockSessionActionHandlerMockRecorder {
	return m.recorder
}

// ProcessSessionAction mocks base method
func (m *MockSessionActionHandler) ProcessSessionAction(action datamodel.SessionAction) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessSessionAction", action)
}

// ProcessSessionAction indicates an expected call of ProcessSessionAction
func (mr *MockSessionActionHandlerMockRecorder) ProcessSessionAction(action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSessionAction", reflect.TypeOf((*MockSessionActionHandler)(nil).ProcessSessionAction), action)
}

// RestoreSession mocks base method
func (m *MockSessionActionHandler) RestoreSession(session datamodel.Session) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RestoreSession", session)
}

// RestoreSession indicates an expected call of RestoreSession
func (mr *MockSessionActionHandlerMockRecorder) RestoreSession(session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreSession", reflect.TypeOf((*MockSessionActionHandler)(nil).RestoreSession), session)
}
