// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/v2/filesystem/ansible.go

// Package mock_filesystem is a generated GoMock package.
package mock_filesystem

import (
	datamodel "github.com/RSE-Cambridge/data-acc/internal/pkg/v2/datamodel"
	filesystem "github.com/RSE-Cambridge/data-acc/internal/pkg/v2/filesystem"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAnsible is a mock of Ansible interface
type MockAnsible struct {
	ctrl     *gomock.Controller
	recorder *MockAnsibleMockRecorder
}

// MockAnsibleMockRecorder is the mock recorder for MockAnsible
type MockAnsibleMockRecorder struct {
	mock *MockAnsible
}

// NewMockAnsible creates a new mock instance
func NewMockAnsible(ctrl *gomock.Controller) *MockAnsible {
	mock := &MockAnsible{ctrl: ctrl}
	mock.recorder = &MockAnsibleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAnsible) EXPECT() *MockAnsibleMockRecorder {
	return m.recorder
}

// CreateEnvironment mocks base method
func (m *MockAnsible) CreateEnvironment(session datamodel.Session, createAllPlaybooks bool, groupAllVars map[string]string) (filesystem.AnsibleEnv, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnvironment", session, createAllPlaybooks, groupAllVars)
	ret0, _ := ret[0].(filesystem.AnsibleEnv)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnvironment indicates an expected call of CreateEnvironment
func (mr *MockAnsibleMockRecorder) CreateEnvironment(session, createAllPlaybooks, groupAllVars interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnvironment", reflect.TypeOf((*MockAnsible)(nil).CreateEnvironment), session, createAllPlaybooks, groupAllVars)
}

// DestroyEnvironment mocks base method
func (m *MockAnsible) DestroyEnvironment(env filesystem.AnsibleEnv) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyEnvironment", env)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyEnvironment indicates an expected call of DestroyEnvironment
func (mr *MockAnsibleMockRecorder) DestroyEnvironment(env interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyEnvironment", reflect.TypeOf((*MockAnsible)(nil).DestroyEnvironment), env)
}

// RunPlaybook mocks base method
func (m *MockAnsible) RunPlaybook(env filesystem.AnsibleEnv, playbook filesystem.AnsiblePlaybook, extraVars map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RunPlaybook", env, playbook, extraVars)
}

// RunPlaybook indicates an expected call of RunPlaybook
func (mr *MockAnsibleMockRecorder) RunPlaybook(env, playbook, extraVars interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPlaybook", reflect.TypeOf((*MockAnsible)(nil).RunPlaybook), env, playbook, extraVars)
}
