// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/v2/registry/pool.go

// Package mock_registry is a generated GoMock package.
package mock_registry

import (
	datamodel "github.com/RSE-Cambridge/data-acc/internal/pkg/v2/datamodel"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPoolRegistry is a mock of PoolRegistry interface
type MockPoolRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockPoolRegistryMockRecorder
}

// MockPoolRegistryMockRecorder is the mock recorder for MockPoolRegistry
type MockPoolRegistryMockRecorder struct {
	mock *MockPoolRegistry
}

// NewMockPoolRegistry creates a new mock instance
func NewMockPoolRegistry(ctrl *gomock.Controller) *MockPoolRegistry {
	mock := &MockPoolRegistry{ctrl: ctrl}
	mock.recorder = &MockPoolRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPoolRegistry) EXPECT() *MockPoolRegistryMockRecorder {
	return m.recorder
}

// GetPools mocks base method
func (m *MockPoolRegistry) GetPools() ([]datamodel.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPools")
	ret0, _ := ret[0].([]datamodel.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPools indicates an expected call of GetPools
func (mr *MockPoolRegistryMockRecorder) GetPools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPools", reflect.TypeOf((*MockPoolRegistry)(nil).GetPools))
}

// EnsurePoolCreated mocks base method
func (m *MockPoolRegistry) EnsurePoolCreated(poolName datamodel.PoolName, granularityGB int) (datamodel.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsurePoolCreated", poolName, granularityGB)
	ret0, _ := ret[0].(datamodel.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsurePoolCreated indicates an expected call of EnsurePoolCreated
func (mr *MockPoolRegistryMockRecorder) EnsurePoolCreated(poolName, granularityGB interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsurePoolCreated", reflect.TypeOf((*MockPoolRegistry)(nil).EnsurePoolCreated), poolName, granularityGB)
}
