// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/fakewarp/job.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockjobCommand is a mock of jobCommand interface
type MockjobCommand struct {
	ctrl     *gomock.Controller
	recorder *MockjobCommandMockRecorder
}

// MockjobCommandMockRecorder is the mock recorder for MockjobCommand
type MockjobCommandMockRecorder struct {
	mock *MockjobCommand
}

// NewMockjobCommand creates a new mock instance
func NewMockjobCommand(ctrl *gomock.Controller) *MockjobCommand {
	mock := &MockjobCommand{ctrl: ctrl}
	mock.recorder = &MockjobCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockjobCommand) EXPECT() *MockjobCommandMockRecorder {
	return m.recorder
}
